### ISSUE TITLE
Catalog API says "URL Blocked"

### ISSUE THREAD

**Issue by Ubiw** [sentanos/rprxy#1]
title.

**Comment by Ubiw** [comment]
https://search.rprxy.xyz/catalog/json?Subcategory=6&ResultsPerPage=25&Keyword=Orange

Comes up with this:

![image](https://user-images.githubusercontent.com/26337371/30005965-c51f42ce-90b3-11e7-9c88-ed632a917019.png)

**Comment by sentanos** [comment]
This is not an issue, this is intended behavior. Because people were spamming catalog requests I had to block them because otherwise ROBLOX would block me for misusing their APIs.
