### ISSUE TITLE
Heroku application error

### ISSUE THREAD

**Issue by noblereign** [sentanos/rprxy#5]
I don't know where to submit this, but apparently rprxy just went down. This is being served whenever i try to visit rprxy or use it in HttpService.

![](https://user-images.githubusercontent.com/2935979/114288179-f8945100-9a21-11eb-88c9-6262274ac19b.png)

**Comment by noblereign** [comment]
nevermind its back up now thanks

**Comment by sentanos** [comment]
No worries, I restarted it when I saw your post. I will be looking into preventing this in the future.

**Comment by noblereign** [comment]
it's happening again (but only with the searchmusic api it seems)
