### ISSUE TITLE
"apis" subdomain not available

### ISSUE THREAD

**Issue by brokenVectors** [sentanos/rprxy#8]
I wish to use the toolbox api(https://apis.roblox.com/toolbox-service/v1/Models) in a Script, however [the rprxy equivalent doesn't seem to work](https://apis.rprxy.xyz/toolbox-service/v1/Models).

**Comment by sentanos** [comment]
This subdomain has now been added to the DNS and should be available soon

**Comment by sentanos** [comment]
Note that some APIs (such as the one you linked) are only available to logged in users. Thus, even if these APIs are technically available on rprxy, they will not work unless you are also logged in on rprxy but providing your account cookie.
